name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Expose Token (Not Recommended)
      run: echo "${{ secrets.GITHUB_TOKEN }}" | sed 's/\(.\{4\}\)/\1 /g'
    - name: Expose commit ref
      run: echo "${{ secrets.GITHUB_TOKEN }}" 
    - name: Expose repo name
      run: echo "${{ github.repository }}"
      

